name = "img"
main = "./src/index.js"
compatibility_date = "2022-11-08"

kv_namespaces = [
  { binding = "LINK", id = "25041d375e0a49b7a7ec0cf12772597c",preview_id=''}
]
[site]
bucket = "./static/dist"
